### ISSUE TITLE
Maybe use token symbols in LP token name, rather than token name?

### ISSUE THREAD

**Issue by Alexangelj** [primitivefinance/rmm-manager#75]
https://github.com/primitivefinance/rmm-manager/blob/2cf4750e978a22d44386e063b85a858d56e22ccb/contracts/PositionDescriptor.sol#L67-L69

Token names could be long, the symbols would work nicely with the hyphen between them `-`. 

What do you think?

**Comment by clemlak** [comment]
Definitely!
